steps:
#step 1 Clone the git repo
- name: 'gcr.io/cloud-builders/git'
  id: 'Clone'
  args: ['clone', 'https://github.com/miftahul-huda/levenshtein-api.git']

#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/$PROJECT_ID/levenshtein-api:$BRANCH_NAME-$COMMIT_SHA',
   '-t', 
   'gcr.io/$PROJECT_ID/levenshtein-api:latest',
   '--build-arg',
   'DBHOST=$$DBHOST',
   '--build-arg',
   'DBNAME=$$DBNAME',
   '--build-arg',
   'DBUSER=$$DBUSER',
   '--build-arg',
   'DBPASSWORD=$$DBPASSWORD',
   '--build-arg',
   'APPLICATION_PORT=$$APPLICATION_PORT',
   '--build-arg',
   'GCP_PROJECT=$$GCP_PROJECT',
   '.'
  ]
  secretEnv: ['DBHOST', 'DBNAME', 'DBUSER', 'DBPASSWORD', 'APPLICATION_PORT' , 'GCP_PROJECT']
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=levenshtein-api-cluster'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'levenshtein-api', 
   'levenshtein-api=gcr.io/$PROJECT_ID/levenshtein-api:$BRANCH_NAME-$COMMIT_SHA'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast2-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=levenshtein-api-cluster'
# push images to Google Container Registry with tags
images: [
   'gcr.io/$PROJECT_ID/levenshtein-api:$BRANCH_NAME-$COMMIT_SHA',
   'gcr.io/$PROJECT_ID/levenshtein-api:latest'
  ]
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/NSN_DBHOST/versions/1
    env: 'DBHOST'
  - versionName: projects/$PROJECT_ID/secrets/NSN_DBNAME/versions/1
    env: 'DBNAME'
  - versionName: projects/$PROJECT_ID/secrets/NSN_DBUSER/versions/1
    env: 'DBUSER'
  - versionName: projects/$PROJECT_ID/secrets/NSN_DBPASSWORD/versions/1
    env: 'DBPASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/NSN_APPPORT/versions/1
    env: 'APPLICATION_PORT'
  - versionName: projects/$PROJECT_ID/secrets/NSN_GCPPROJECT/versions/1
    env: 'GCP_PROJECT'