apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: levenshtein
  name: levenshtein
spec:
  replicas: 2
  selector:
    matchLabels:
      run: levenshtein
  template:
    metadata:
      labels:
        run: levenshtein
    spec:
      containers:
      - image: gcr.io/huda-playground/levenshtein:latest
        name: levenshtein
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: levenshtein-config