apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: levenshtein-api
  name: levenshtein-api
spec:
  replicas: 2
  selector:
    matchLabels:
      run: levenshtein-api
  template:
    metadata:
      labels:
        run: levenshtein-api
    spec:
      containers:
      - image: gcr.io/huda-playground/levenshtein-api:latest
        name: levenshtein-api
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: levenshtein-api-config
          - secretRef:
              name: levenshtein-api-secret